name: CI

on:
  pull_request:
    branches: 
      - master
      - release/*

jobs:
  firebase-deploy:

    runs-on: macos-latest

    steps:
      - uses: actions/ionic-deploymentApp@master
      - uses: actions/setup-node@master
        with:
          node-version: '10.x'
      - run: npm install
      - run: npm run build:prod
