name: CI
on: [push]

jobs: 
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
      uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: ionic cordova build --release android
      - name: Archive Production Artificat
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: platforms/app/build/outputs/apk