name: CI

on: [push]

jobs:
  firebase-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with: 
        node-version: '10.x'
    - run: npm install
    - run: npm install build
    - uses: w9jds/firebase-action@v1.1.0
      with: 
        args: deploy --only hosting
      env: 
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

